version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/infinitek
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=8883
      - MQTT_TLS=true
      - MQTT_TLS_INSECURE=true
      - JWT_SECRET=${JWT_SECRET:-changeme}
      - API_PREFIX=/api
      - CORS_ORIGINS=*
      - USE_S3_OTA=${USE_S3_OTA:-false}
      - S3_BUCKET=${S3_BUCKET:-}
      - S3_REGION=${S3_REGION:-}
      - S3_URL_EXPIRES=${S3_URL_EXPIRES:-900}
    ports:
      - "8000:8000" # remove in prod; use nginx
    depends_on:
      - db
      - mosquitto
    env_file:
      - backend/.env
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=infinitek
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config:ro
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
  prometheus:
    image: prom/prometheus:v2.55.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:11.3.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
volumes:
  db_data:
  mosquitto_data:
  mosquitto_log:
